### ISSUE TITLE
StackOverflowError when merging tracks in opposite direction

### ISSUE THREAD

**Issue by bjoeni** [archwheeler/bus-route-maintenance#9]
SOE in `curveSegment()` occurs when the segments that should be averaged are in opposite directions: [merge-sample.gpx](https://github.com/archwheeler/bus-route-maintenance/files/6586094/merge-sample.gpx.txt)

```
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2021-05-27 19:45:08 +0200 (Thu, 27 May 2021)
Build-Date:2021-05-28 01:31:01
Revision:17915
Relative:URL: ^/trunk

Identification: JOSM/1.5 (17915 en) Windows 10 64-Bit
OS Build number: Windows 10 Home 2009 (21390)
Memory Usage: 1381 MB / 3580 MB (723 MB allocated, but free)
Java version: 1.8.0_271-b09, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Look and Feel: com.formdev.flatlaf.FlatDarkLaf
Screen: \Display0 1920×1080 (scaling 1.00×1.00) \Display1 2560×1440 (scaling 1.00×1.00)
Maximum Screen Size: 2560×1440
Best cursor sizes: 16×16→32×32, 32×32→32×32
System property file.encoding: Cp1252
System property sun.jnu.encoding: Cp1252
Locale info: en_DE
Numbers with default locale: 1234567890 -> 1234567890
VM arguments: [-Djava.security.manager, -Djava.security.policy=file:<java.home>\lib\security\javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>\bin, -Djnlpx.origFilenameArg=%UserProfile%\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\31\583aa85f-30657c12, -Djnlpx.remove=false, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlpx.splashport=53399, -Djnlp.application.href=https://josm.openstreetmap.de/download/josm-latest.jnlp, -Djnlpx.jvm=<java.home>\bin\javaw.exe]

Plugins:
+ BusRouteMaintenance (1619878317)
+ InfoMode (35543)
+ apache-commons (35524)
+ flatlaf (35734)
+ photo_geotagging (35738)
+ photoadjust (35770)

Last errors/warnings:
- 00076.466 E: Failed to locate image 'Waypoint'
- 00076.467 E: Failed to locate image 'Waypoint'
- 00076.490 E: Failed to locate image 'Waypoint'
- 00076.492 E: Failed to locate image 'Waypoint'
- 00076.508 E: Failed to locate image 'Waypoint'
- 00076.509 E: Failed to locate image 'Waypoint'
- 00205.403 E: Handled by bug report queue: java.lang.StackOverflowError
- 02007.961 E: Handled by bug report queue: java.lang.StackOverflowError
- 02093.451 E: Handled by bug report queue: java.lang.StackOverflowError
- 02107.617 E: Handled by bug report queue: java.lang.StackOverflowError



=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-2 (56) of javawsApplicationThreadGroup
java.lang.StackOverflowError
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at busroutemaintenance.DivideConquerAverageTracks.curveSegment(DivideConquerAverageTracks.java:173)
	at busroutemaintenance.DivideConquerAverageTracks.curveSegment(DivideConquerAverageTracks.java:177)
	at busroutemaintenance.DivideConquerAverageTracks.curveSegment(DivideConquerAverageTracks.java:177)
	at busroutemaintenance.DivideConquerAverageTracks.curveSegment(DivideConquerAverageTracks.java:177)
	at busroutemaintenance.DivideConquerAverageTracks.curveSegment(DivideConquerAverageTracks.java:177)
        ...
```

**Comment by archwheeler** [comment]
Hey, thanks for checking out my plug-in! I managed to recreate the bug with your sample data. I've now added a stable 'basic' option to the averaging action in [v1.1.0](https://github.com/archwheeler/bus-route-maintenance/releases/tag/v1.1.0) which achieves a good result using your data with no crashes:

![better](https://user-images.githubusercontent.com/8657895/121527925-db183f00-c9f2-11eb-8f3d-fa32facad25d.png)

I hope this helps!
